// [GET]
export const GET_ALL_SHORT_LINKS = "GET_ALL_SHORT_LINKS";
// [POST]
export const GENERATE_SHORT_LINK_FROM_URL = "GENERATE_SHORT_LINK_FROM_URL";
export const GET_SHORT_LINK_BY_HASH = "GET_SHORT_LINK_BY_HASH";
// [PUT]
export const CHANGE_SHORT_LINK_INFO = "CHANGE_SHORT_LINK_INFO";
// [DELETE]
export const DELETE_SHORT_LINK = "DELETE_SHORT_LINK";